- name: Create operating system group
  hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- name: Run on CentOS hosts only
  hosts: os_Linux
  tasks:
  - name: Install Apache
    yum: 
      name=httpd 
      state=latest

- name: Run on Ubuntu hosts only
  hosts: os_Linux
  tasks:
  - name: Install Apache
    yum: 
      name=apache2 
      state=latest
