- hosts: server
  become: yes
  tasks: 
  - name: default verbose
    debug: 
      msg: This is a test message without verbosity
  
  - name: verbosity level 1
    debug:
      msg: this a test message with verbosity level 1
      verbosity: 1
