- hosts: node
  become: yes
  tasks:
  - name: creating directory for maven
    file:
      path: /opt/maven/
      state: directory

  - name: installing maven
    get_url:
      url: https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /opt/maven

  - name: unarchive the tar file
    unarchive:
      src: /opt/maven/apache-maven-3.6.3-bin.tar.gz
      dest: /opt/maven
      remote_src: yes

  - name: install maven
    yum:
      name: maven
      state: present
 
