- hosts: node
  become: yes
  tasks: 
  - name: creating  multiple files
    file:
      path: "{{ item }}"
      state: touch
      mode: 0775
    with_items:
    - access.log
    - system.log
    - properties.txt	
    - conffile.conf
