- hosts: ap-south-1
  become: yes
  tasks:
   - name: installing nginx
     command: amazon-linux-extras install nginx1.12=latest -y
     args:
       chdir: /usr/share/
   
   - name: insert index page
     copy:
       src: index.html
       dest: /usr/share/nginx/html/index.html
     notify:
     - Restart nginx

   - name: start nginx
     service:
       name: nginx
       state: started
  handlers:
     - name: Restart nginx
       service:
         name: nginx
         state: restarted   
