- hosts: all
  become: yes
  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no

    - name: password
      prompt: enter your password
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7

  tasks:

    - name: Print a message
      debug:
        msg: 'Logging in as {{ username }}'
